#!/usr/bin/env bash
set -xo pipefail

pomodoroStatus="$(/nix/store/pmgcjwrd2vp5hh9s7n7kxflqz716sji0-openpomodoro-cli-0.3.0/bin/pomodoro history | /nix/store/5156mw0rs30bzxi478dslmhmxr2d8vww-coreutils-full-9.5/bin/tail -2)"
/nix/store/vzjx8rzzm09g87w9nh4831mf7xxmzd59-libnotify-0.8.3/bin/notify-send "Pomodoro start 🚀" "<b>$pomodoroStatus</b>" &
sleep "$(/nix/store/5156mw0rs30bzxi478dslmhmxr2d8vww-coreutils-full-9.5/bin/tail -n 1 /home/alice/.pomodoro/history | /nix/store/lvnwdmnjm7nvaq0a3vhvvn46iy4ql7gr-gnugrep-3.11/bin/grep -oP 'duration=\K[0-9]+')"m
/nix/store/40mb4yjaa3zydd9vbr7mh01m2yifxbl6-pipewire-1.2.5/bin/pw-play /home/alice/.pomodoro/hooks/music.mp3
pomodoroStatus="$(/nix/store/pmgcjwrd2vp5hh9s7n7kxflqz716sji0-openpomodoro-cli-0.3.0/bin/pomodoro history | /nix/store/5156mw0rs30bzxi478dslmhmxr2d8vww-coreutils-full-9.5/bin/tail -2)"
/nix/store/vzjx8rzzm09g87w9nh4831mf7xxmzd59-libnotify-0.8.3/bin/notify-send "Pomodoro finished ✅🏁" "<b>$pomodoroStatus</b>"    
